#!/usr/bin/env bash
# Comment on the PR only when it needs a human, so a green PR stays silent.
# Docs: docs/runbooks/setup-operations/renovate-pr-review.md

set -uo pipefail
body="$RUNNER_TEMP/comment.md"
{
  # Marker: lets a re-run replace its own comment instead of stacking one per
  # `synchronize`. The verdict lives in the status, not here.
  echo "<!-- renovate-image-delta -->"
  echo '## What actually changed in these images'
  echo
  sed '/^DELTA: /d' "$DELTA_REPORT"
  if [ "$GATE" = "true" ] && [ -s "${AGENT_REPORT:-/dev/null}" ]; then
    echo
    echo '## Upstream risk assessment'
    echo
    cat "$AGENT_REPORT"
    echo
    echo "<sub>$AGENT_USAGE</sub>"
  fi
  echo
  if [ "$STATE" != "success" ]; then
    echo "**Needs you** — $REASON. \`renovate-review\` is red, so this one will not be swept up at 05:00 and the required check holds it back from a hand-merge until you override it deliberately."
  elif [ "$AUTOMERGE" = "true" ]; then
    echo "**Cleared to auto-merge** — $REASON. It merges in the next 05:00-06:00 Berlin window, so the redeploy lands while nothing is using the NAS."
  else
    echo "**Nothing to review** — $REASON."
  fi
  echo
  echo '<sub>Generated by <a href="../blob/main/.github/workflows/renovate-pr-review.yml">renovate-pr-review</a>.</sub>'
} > "$body"

# --jq runs per page, so take the first id. Prefix match: old markers carry `automerge=`.
existing=$(gh api "repos/$REPO/issues/$PR/comments" --paginate \
  --jq '.[] | select(.body | startswith("<!-- renovate-image-delta")) | .id' 2>/dev/null \
  | head -n 1 || true)

if [ -n "$existing" ]; then
  # An edit does not notify, so keeping an existing comment current is free.
  gh api -X PATCH "repos/$REPO/issues/comments/$existing" -F body=@"$body" >/dev/null \
    && echo "updated comment $existing" || echo "::warning::could not update comment"
elif [ "$STATE" != "success" ]; then
  gh api -X POST "repos/$REPO/issues/$PR/comments" -F body=@"$body" >/dev/null \
    && echo "posted new comment" || echo "::warning::could not post comment"
else
  echo "cleared and no existing comment — staying silent by design."
fi
